### ISSUE TITLE
update: v3.14

### ISSUE THREAD

**Issue by renich** [bitwigstudio/bitwig-overlay#2]
I've added v3.14 to the testing branch. Would you have a look at it?

it is important since I've changed a ton of things; with better support and locations for certain stuff.

**Comment by Ridderby** [comment]
Hi Renich, 

Sorry I have been busy lately and never got around look at the v3.14 ebuild. 

I have now looked at and tested the new ebuild and it seems good. In particular I keep an eye on the gnome2-functions and if they would mess up for me running KDE :)

The only thing is the slot-change. I don't recall why I put slot 3 in the earlier versions or if that was an mistake, anyway you changed to 0. This is in general fine unless you make an upgrade from the version 3.13 [3] as portage tries to install them in parallel resulting in a ton of collision. I am fine with that but would like to have a message that file collisions is likely to be caused by the slot change and is solved doing an uninstall before install. 
I have not verified that downloaded materials from Bitwig (loops, sounds, samples etc) remains after an uninstall/install. If I reinstall my computer I will always need to download them again even though I use the very same home. Anyway uninstall/install solved all file collissions. 

Was it intentional to keep the fetch restriction? I just lacked the download-link and wanted proper handling of manually downloaded stuff. We might consider adding a licence to licence-accept instead and allow for automatic downloads now there is a link. 

// Erik

**Comment by renich** [comment]
> Hi Renich,
>
>Sorry I have been busy lately and never got around look at the v3.14 ebuild.

Hey man! No worries. I have been, pretty much, the same.

>I have now looked at and tested the new ebuild and it seems good. In particular I keep an eye on the gnome2-functions and if they would mess up for me running KDE :)

OK. Is there anything to do about this on my side?

>The only thing is the slot-change. I don't recall why I put slot 3 in the earlier versions or if that was an mistake, anyway you changed to 0. This is in general fine unless you make an upgrade from the version 3.13 [3] as portage tries to install them in parallel resulting in a ton of collision. I am fine with that but would like to have a message that file collisions is likely to be caused by the slot change and is solved doing an uninstall before install.
> I have not verified that downloaded materials from Bitwig (loops, sounds, samples etc) remains after an uninstall/install. If I reinstall my computer I will always need to download them again even though I use the very same home. Anyway uninstall/install solved all file collissions.

https://devmanual.gentoo.org/general-concepts/slotting/

In our case, we do not several versions installed. This is why I am going for SLOT="0". Let me know what you think but, IMHO, this is the right setting.

>Was it intentional to keep the fetch restriction? I just lacked the download-link and wanted proper handling of manually downloaded stuff. We might consider adding a licence to licence-accept instead and allow for automatic downloads now there is a link.

I didn't quite get you with the fetch restriction. 

The licence-acept idea is a good idea.
